### PR TITLE
Add support for the 'reference' statement under import.

### PR DESCRIPTION
**Pull request by robshakir**
This change adds support for the YANG 1.1 construct:

```yang
import foo {
  prefix "bar";
  reference "bat";
}
```

to goyang. The test added provides an extensible way to add tests for the contents of opaque `Node` structures to the goyang pkg.

### CODE REVIEW

**Comment by guilt** [comment]
We should add a description field as well, and get it in!

**Comment by LeonGWang** [comment]
Hey Rob, the `reference` statement addition looks like a duplicate of PR #78. Why don't we just add tests for import's `reference` and `description` sub-statements using the test framework you have developed here?

**Comment by robshakir** [comment]
@guilt @LeonGWang @andaru -- PTAL, and we can go ahead and merge this. Added support for `import { description ... }`.

**Comment by LeonGWang** [comment]
Hey Rob, thanks for the quick response. This looks great to me! Let's merge this.

**Comment by robshakir** [comment]
Thanks for the reviews.

**Comment by robshakir** [comment]
Thanks for the reviews.

**Comment by robshakir** [comment]
Thanks for the reviews! Merged.

**Comment by robshakir** [comment]
Sorry for the duplicate messages -- transaltantic wifi issues.

**Pull request merged**
